services:
  keycloak_demo:
    image: quay.io/keycloak/keycloak:25.0.2
    command: start-dev
    environment:
      KC_DB: postgres
      KC_DB_URL_HOST: postgres_keycloak_demo
      KC_DB_URL_DATABASE: keycloak
      KC_DB_PASSWORD: password
      KC_DB_USERNAME: keycloak
      KC_DB_SCHEMA: public
      KEYCLOAK_ADMIN: admin
      KEYCLOAK_ADMIN_PASSWORD: admin
    ports:
      - "8890:8080"
    depends_on:
      postgres_keycloak_demo:
        condition: service_healthy
    networks:
      - keycloak_demo_dev_network

  postgres_keycloak_demo:
    image: postgres:16.3
    command: postgres -c "max_connections=200"
    volumes:
      - pgdata_keycloak_data:/var/lib/postgresql/data
    environment:
      POSTGRES_DB: keycloak
      POSTGRES_USER: keycloak
      POSTGRES_PASSWORD: password
    healthcheck:
      test: "exit 0"
    ports:
      - "5436:5432"
    networks:
      - keycloak_demo_dev_network

  lambda-node:
    build: ./lambda-node
    ports: 
      - "9000:8080"
    depends_on:
      - keycloak_demo
    networks:
      - keycloak_demo_dev_network

  lambda-java-getsessions:
    build: ./lambda-java/getsessions
    ports: 
      - "9100:8080"
    depends_on:
      - keycloak_demo
    networks:
      - keycloak_demo_dev_network

  lambda-java-terminatesessions:
    build: ./lambda-java/terminatesessions
    ports: 
      - "9200:8080"
    depends_on:
      - keycloak_demo
    networks:
      - keycloak_demo_dev_network
      

      
volumes:
  pgdata_keycloak_data:
networks:
  keycloak_demo_dev_network:
    driver: bridge

